#!/usr/bin/env node
/* P17a PWA prebuild stamp (npm `prebuild` hook, runs after gen-content).
   Replaces the finance @PUBLISH@ PHP relic with a build-time stamp:
   - BUILD_ID = pkg version + git short SHA (fallback: unix time), e.g. "0.6.32-a1b2c3d".
   - public/sw.js: source public/sw.src.js with __BUILD_ID__ replaced -> unique
     cache namespaces per deploy; activate purges the old ones.
   - public/manifest.webmanifest: source public/manifest.src.json with __BUILD_ID__
     -> fresh URL so install metadata busts with the release.
   Both outputs keep RELATIVE "./" start_url/scope/icon paths: GitHub Pages serves
   /androidscroll-site/ and apex later serves / from the same tree, and relative
   manifest URLs resolve per-location (verified v0.6.31 served bytes). No per-env
   files needed. Exits non-zero if a source token is missing (never ship a stub). */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

let sha = '';
try {
  sha = execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim();
} catch {}
const BUILD_ID = `${pkg.version}-${sha || Date.now().toString(36)}`;

function stamp(src, dest, json) {
  const s = readFileSync(join(ROOT, src), 'utf8');
  if (!s.includes('__BUILD_ID__')) {
    console.error(`stamp-pwa: FATAL ${src} has no __BUILD_ID__ token`);
    process.exit(1);
  }
  const out = s.replace(/__BUILD_ID__/g, BUILD_ID);
  if (json) JSON.parse(out); // never emit a broken manifest
  writeFileSync(join(ROOT, dest), out);
}

stamp('public/sw.src.js', 'public/sw.js');
stamp('public/manifest.src.json', 'public/manifest.webmanifest', true);
stamp('public/pwa-install.src.js', 'public/pwa-install.js');

// Build-id module for Head.astro's manifest link (?v=BUILD_ID -> install
// metadata busts with the release alongside the SW).
writeFileSync(
  join(ROOT, 'src', 'data', 'pwa-stamp.ts'),
  `// GENERATED by scripts/stamp-pwa.mjs at prebuild - do not edit.\nexport const BUILD_ID = '${BUILD_ID}';\n`
);
console.log(`stamp-pwa: BUILD_ID=${BUILD_ID} -> sw.js + pwa-install.js + manifest.webmanifest + pwa-stamp.ts`);
